export const menu = {
  categories: ["Starters", "Mains", "Sushi & Rolls", "Sides", "Drinks", "Desserts"],
  items: [
    // Starters
    {
      id: "edamame",
      name: "Steamed Edamame",
      category: "Starters",
      price: 6.0,
      description: "Sea salt dusted, lightly steamed",
      emoji: "🫛",
      tags: ["vegan", "gluten-free"],
      spicy: false,
    },
    {
      id: "gyoza",
      name: "Pan-Fried Gyoza",
      category: "Starters",
      price: 11.0,
      description: "Pork & cabbage dumplings, ponzu dipping sauce",
      emoji: "🥟",
      tags: [],
      spicy: false,
    },
    {
      id: "spring-rolls",
      name: "Crispy Spring Rolls",
      category: "Starters",
      price: 10.0,
      description: "Vegetable & glass noodle, sweet chili sauce",
      emoji: "🌯",
      tags: ["vegan"],
      spicy: false,
    },
    {
      id: "miso-soup",
      name: "Miso Soup",
      category: "Starters",
      price: 5.0,
      description: "White miso, tofu, wakame, scallions",
      emoji: "🍲",
      tags: ["vegan"],
      spicy: false,
    },
    {
      id: "chicken-satay",
      name: "Chicken Satay",
      category: "Starters",
      price: 13.0,
      description: "4 skewers, peanut sauce, cucumber relish",
      emoji: "🍢",
      tags: [],
      spicy: false,
    },
    {
      id: "spicy-tuna-crispy-rice",
      name: "Spicy Tuna Crispy Rice",
      category: "Starters",
      price: 16.0,
      description: "Seared sushi rice, spicy tuna, jalapeño",
      emoji: "🍱",
      tags: [],
      spicy: true,
    },

    // Mains
    {
      id: "wagyu-ramen",
      name: "Wagyu Beef Ramen",
      category: "Mains",
      price: 28.0,
      description: "Rich tonkotsu broth, wagyu slices, soft egg, bamboo",
      emoji: "🍜",
      tags: [],
      spicy: false,
    },
    {
      id: "pad-thai",
      name: "Classic Pad Thai",
      category: "Mains",
      price: 19.0,
      description: "Rice noodles, tamarind, tofu, peanuts, bean sprouts",
      emoji: "🍝",
      tags: ["vegan-optional"],
      spicy: false,
    },
    {
      id: "kung-pao-chicken",
      name: "Kung Pao Chicken",
      category: "Mains",
      price: 22.0,
      description: "Wok-fried chicken, dried chilies, peanuts, Sichuan peppercorn",
      emoji: "🍗",
      tags: [],
      spicy: true,
    },
    {
      id: "miso-glazed-salmon",
      name: "Miso Glazed Salmon",
      category: "Mains",
      price: 26.0,
      description: "White miso marinade, bok choy, steamed jasmine rice",
      emoji: "🐟",
      tags: ["gluten-free"],
      spicy: false,
    },
    {
      id: "korean-bbq-bowl",
      name: "Korean BBQ Bowl",
      category: "Mains",
      price: 23.0,
      description: "Bulgogi beef, kimchi, cucumber, sesame rice, gochujang",
      emoji: "🥩",
      tags: [],
      spicy: true,
    },
    {
      id: "green-curry",
      name: "Thai Green Curry",
      category: "Mains",
      price: 20.0,
      description: "Coconut milk, vegetables, Thai basil, jasmine rice",
      emoji: "🍛",
      tags: ["vegan"],
      spicy: true,
    },

    // Sushi & Rolls
    {
      id: "spicy-tuna-roll",
      name: "Spicy Tuna Roll",
      category: "Sushi & Rolls",
      price: 15.0,
      description: "Tuna, spicy mayo, cucumber, tobiko (8 pcs)",
      emoji: "🍣",
      tags: [],
      spicy: true,
    },
    {
      id: "dragon-roll",
      name: "Dragon Roll",
      category: "Sushi & Rolls",
      price: 18.0,
      description: "Shrimp tempura, avocado, eel sauce (8 pcs)",
      emoji: "🐉",
      tags: [],
      spicy: false,
    },
    {
      id: "rainbow-roll",
      name: "Rainbow Roll",
      category: "Sushi & Rolls",
      price: 19.0,
      description: "California base, assorted fish, avocado (8 pcs)",
      emoji: "🌈",
      tags: [],
      spicy: false,
    },
    {
      id: "veggie-roll",
      name: "Garden Veggie Roll",
      category: "Sushi & Rolls",
      price: 12.0,
      description: "Avocado, cucumber, carrot, pickled radish (8 pcs)",
      emoji: "🥑",
      tags: ["vegan"],
      spicy: false,
    },

    // Sides
    {
      id: "steamed-rice",
      name: "Steamed Jasmine Rice",
      category: "Sides",
      price: 4.0,
      description: "Fragrant Thai jasmine rice",
      emoji: "🍚",
      tags: ["vegan", "gluten-free"],
      spicy: false,
    },
    {
      id: "fried-rice",
      name: "Wok Fried Rice",
      category: "Sides",
      price: 7.0,
      description: "Egg fried rice, soy, scallions",
      emoji: "🍳",
      tags: [],
      spicy: false,
    },
    {
      id: "bok-choy",
      name: "Garlic Bok Choy",
      category: "Sides",
      price: 8.0,
      description: "Baby bok choy, garlic oil, oyster sauce",
      emoji: "🥬",
      tags: ["vegan-optional"],
      spicy: false,
    },

    // Drinks
    {
      id: "jasmine-tea",
      name: "Jasmine Green Tea",
      category: "Drinks",
      price: 4.0,
      description: "Hot or iced, lightly floral",
      emoji: "🍵",
      tags: ["vegan"],
      spicy: false,
    },
    {
      id: "matcha-latte",
      name: "Matcha Latte",
      category: "Drinks",
      price: 6.0,
      description: "Ceremonial grade matcha, oat milk",
      emoji: "🍃",
      tags: ["vegan"],
      spicy: false,
    },
    {
      id: "lychee-mojito",
      name: "Lychee Mojito (Mocktail)",
      category: "Drinks",
      price: 8.0,
      description: "Fresh lychee, mint, lime, soda water",
      emoji: "🍹",
      tags: ["vegan"],
      spicy: false,
    },
    {
      id: "sake",
      name: "House Sake",
      category: "Drinks",
      price: 10.0,
      description: "Warm or chilled, clean finish",
      emoji: "🍶",
      tags: [],
      spicy: false,
    },
    {
      id: "water",
      name: "Still Water",
      category: "Drinks",
      price: 2.0,
      description: "Chilled still water",
      emoji: "💧",
      tags: ["vegan"],
      spicy: false,
    },

    // Desserts
    {
      id: "mochi-ice-cream",
      name: "Mochi Ice Cream (3pc)",
      category: "Desserts",
      price: 9.0,
      description: "Mango, matcha, strawberry — choose or assorted",
      emoji: "🍡",
      tags: [],
      spicy: false,
    },
    {
      id: "black-sesame-cake",
      name: "Black Sesame Cake",
      category: "Desserts",
      price: 11.0,
      description: "Dense, nutty, cream cheese frosting",
      emoji: "🎂",
      tags: [],
      spicy: false,
    },
    {
      id: "mango-sticky-rice",
      name: "Mango Sticky Rice",
      category: "Desserts",
      price: 10.0,
      description: "Sweet coconut sticky rice, fresh mango, sesame",
      emoji: "🥭",
      tags: ["vegan", "gluten-free"],
      spicy: false,
    },
  ],
};
